apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  template:
    spec:
     containers:
      - env:
        - name: COUCHDB_PASSWORD
          value: password
        - name: COUCHDB_USER
          value: admin
        name: db