version: "3.7"

services:
  hobbes:
    image: kmdrd/hobbes-hobbes.server
    container_name: hobbes
    expose:
      - 8085
    ports:
      - 8085:8085
    environment:
      - COUCHDB_USER=admin 
      - COUCHDB_PASSWORD=password
      - SERVER_PORT=8085
      - KEY_SUFFIX=2804de67ba6979c756e8759e44fe4
      - DB_SERVER_URL=http://db:5984/
      - AZURE_TOKEN=abcdef
  db:
    image: apache/couchdb
    container_name: db
    environment:
      - COUCHDB_USER=admin 
      - COUCHDB_PASSWORD=password
    expose: 
      - 5984
    volumes:
      - ./db/data:/opt/couchdb/data
    ports:
      - 5984:5984
  oauth:
    build:
      context: ./oauth
      dockerfile: Dockerfile
    container_name: oauth
    expose: 
      - 4180
    command: "--email-domain=* -cookie-secure=false -client-id=de431b1775741ace6e15 -redirect-url=https://localhost:8443/oauth2/callback --provider=github --http-address=http://0.0.0.0:4180 -upstream http://hobbes:8085 -client-secret=0a7e17f20beed0849045eb98292858f102442474 -github-org=r-d-kmd -cookie-secret=SECRETSECRET"
    #command: "--email-domain=* --provider=azure --http-address=http://0.0.0.0:4180 -upstream http://hobbes:8085 -client-secret=*******"
  front:
    container_name: front
    image: kmdrd/hobbes-front
    ports:
      - 8443:443
      - 8080:80
