FROM mcr.microsoft.com/dotnet/core/aspnet:3.0
RUN apt-get update
RUN apt-get install -y unzip procps 
RUN curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l ~/vsdbg
COPY /src/deploy /
WORKDIR /Server
ENTRYPOINT [ "dotnet", "hobbes.server.dll" ]