version: "3.7"
networks:
  internal:

services:

  hobbes:
    image: hobbes
    #build:
    #    context: ./src
    #    dockerfile: Dockerfile
    container_name: hobbes
    networks: 
      - internal
    expose:
      - 8085
    ports:
      - 8085:8085

  db:
    image: apache/couchdb
    container_name: db
    environment:
      - COUCHDB_USER=admin 
      - COUCHDB_PASSWORD=password
    networks: 
      - internal
    expose: 
      - 5984
    volumes:
      - ./db/data:/opt/couchdb/data
    ports:
      - 5984:5984

  nginx:
    image: nginx
    networks: 
      - internal
    ports:
      - 8080:80
    depends_on:
      - hobbes
      - db
