version: 1.0.{build}
image: Visual Studio 2019

environment:
  DOCKER_USER:
    secure: CbwbpNPxLV9AwhjSpIz7LA==
  DOCKER_PASS:
    secure: /T9ITfudL23Ga+Mz7oRaVA==
  
install:
  - docker version
  - dotnet tool install fake-cli -g
  - dotnet tool install --global --version 5.198.0 paket

before_build:
  - paket install
  - mkdir "c:\projects\hobbes\hobbes.server\db"
  - mkdir "c:\projects\hobbes\hobbes.server\db\data"

build_script: 
  - fake build --target build
  - fake build --target builddocker

test_script:
  - fake build --target test

deploy_script:
  - docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
  - fake build --target pushtodocker

