version: 1.0.{build}
image: Visual Studio 2019

environment:
  DOCKER_USER:
    secure: CbwbpNPxLV9AwhjSpIz7LA==
  DOCKER_PASS:
    secure: /T9ITfudL23Ga+Mz7oRaVA==
  WORKBENCH_ENVIRONMENT:
    secure: 4r5rqR4feMdZH8NeoYqKl1IYLb3orco46/LB1r7LjcNTTL9QSOTh3OpvlijK1eYMJTr5KlOlbsDz/v2StyaZgdiTq7mqsRWviHyg8/Kqk+2aylHuok0T/vNezyzogCA+3lR5qhRLmXqrM08Z8UJ4iz0HtFJz1INAcZpoAJFP1oMJy6ej6/t7RsQTLSFnc0zYWNAKRJK6sk5FnYjF4CnqtFFBpwYHB5HX4kbUn3BgvJDVDRXxoq9musddl33RaDogO/ynInby6JqFlRrHUGNFvjZnjxV9571/4b4p+D/ZfENOny2BpQnotccArCc8M0kp8NCxx0vB14S+ToIM9y90ccmNMSSalIYaOBVTqZ2eSRTHah+ZKbB79/n8395O+Mor07fPEqSF9HWCSYihGapshO8PaT8MNF8wVvnfcL7lfA8=

dotnet_csproj:
  patch: true
  file: '**\hobbes.server.fsproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
install:
  - docker version
  - dotnet tool install fake-cli -g
  - dotnet tool install --global --version 5.198.0 paket

before_build:
  - paket install
  - mkdir "c:\projects\hobbes\hobbes.server\db\data"

build_script: 
  - fake build --target build
  - fake build --target builddocker

test_script:
  - fake build --target test

after_test:
  - npm install -s -g --unicode=false newman
  - newman run --disable-unicode .\hobbes.server\db\Postman_collections\Smoktests.json -e .\hobbes.server\db\Postman_collections\Production_environment.json

deploy_script:
  - docker login -u="%DOCKER_USER%" -p="%DOCKER_PASS%"
  #- fake build --target Publish

