version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: xxxxxxx
  DOCKER_PASS:
    secure: yyyyyyy

install:
  - docker version
  - dotnet tool install fake-cli -g
  - dotnet tool install --global --version 5.198.0 paket

before_build:
  - paket install

build_script: 
  - fake build --target build

test_script:
  - fake build --target systemtest

#deploy_script:
#  - docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
#  - fake build --target pushtodocker

