version: 1.0.{build}
image: Visual Studio 2019

environment:
  DOCKER_USER:
    secure: CbwbpNPxLV9AwhjSpIz7LA==
  DOCKER_PASS:
    secure: /T9ITfudL23Ga+Mz7oRaVA==

dotnet_csproj:
  patch: true
  file: '**\hobbes.server.fsproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
install:
  - docker version
  - dotnet tool install fake-cli -g
  - dotnet tool install --global --version 5.198.0 paket

before_build:
  - paket install
  - mkdir "c:\projects\hobbes\hobbes.server\db\data"

build_script: 
  - fake build --target build
  - fake build --target builddocker

test_script:
  - fake build --target test

deploy_script:
  - docker login -u="%DOCKER_USER%" -p="%DOCKER_PASS%"
  - fake build --target pushtodocker

