version: 2.0.{build} 
image: 
  - Ubuntu

branches:
  only:
    - development
environment:
  BUILD_ENV: AppVeyor
  ENV_FILE:
    secure: 1EY0PW6l+4E/ZiuaRlC8WHb8v2J6o+YWksH852D5wIVfRnWBC6Ih6bPQMSwQ1Smm71oEOrsd8WJsabgdIkZIxinJ4chtLNBEjx2Wm32JuQziI+jvxc+Q+9YUtwrijB6xP2jHPA0n5wLEE1yHiicn6FFTFcXMJnOpizKcVkU9CgAywwJC+hXp17Vmp96jkfoDem7ZnOpSfUplJti7Vw55aHz4IkkP/G60d+9ak2cks3SHXE80y4ouOnULCZbr2JwekIbxOCJjgOBGeUu7X2hGNMd1u9z00M3iqyS6cwIwnlea5x8cGJrO2XYQ00PCUkzlmGjdeGN5S5In5e7T7VB2aUew383/xTgOzlnUXICso8TmCXibR7hoIm33sE7Uf+RlCboVQWvcBnnCFWmsFhenkl9w2x6Ub7/RUb+f+p8jHTLVtWp5OqDP08kvnBP+vcGWZtCDE8m1UGP5coniBWcrMJdGxanOl9TIicKHJaMpb3AAri9f8GZ8VkF1XaKRWnm/Vk9MA6AgHi2UeMJ7xHf8T8lgcyFMIOi8sPzjlipmQ8HTReazYOvrsdbQp0cMx+Ds1e054B11GrytHMOBt5dXBOu42s2X8rzp9Ish3WqMQVrF6FacQY/34n+ZiOE4Trq4D/7tuOZGlnSS3nscnt9h9dCtZK109jiSE9RyHViGIAgVtN/91bpxxcUME3epyKN4qU1/Afxmf6xGbyn0pjTz6cmPpPrh7eX/Ka5UIBBahoyk+v0b7zoVpqNQ/9y2F6xpnYqltqx5Ukkp2iSfqTPHx50dwWbHlVPhODfXdfXnEQ03vr6YDzNoJd2rGoyXH+mUp2iQFGnIN/0ihHJsEzPj3Q==
    #secure: 1EY0PW6l+4E/ZiuaRlC8WHb8v2J6o+YWksH852D5wIVfRnWBC6Ih6bPQMSwQ1Smm71oEOrsd8WJsabgdIkZIxinJ4chtLNBEjx2Wm32JuQziI+jvxc+Q+9YUtwrijB6xP2jHPA0n5wLEE1yHiicn6FFTFcXMJnOpizKcVkU9CgAywwJC+hXp17Vmp96jkfoDem7ZnOpSfUplJti7Vw55aHz4IkkP/G60d+9ak2cks3SHXE80y4ouOnULCZbr2JwekIbxOCJjgOBGeUu7X2hGNMd1u9z00M3iqyS6cwIwnlea5x8cGJrO2XYQ00PCUkzlmGjdeGN5S5In5e7T7VB2aUew383/xTgOzlnUXICso8TmCXibR7hoIm33sE7Uf+RlCboVQWvcBnnCFWmsFhenkl9w2x6Ub7/RUb+f+p8jHTLVtWp5OqDP08kvnBP+vcGWZtCDE8m1UGP5coniBWcrMJdGxanOl9TIicKHJaMpb3AAri9f8GZ8VkF1XaKRWnm/Vk9MA6AgHi2UeMJ7xHf8T8lgcyFMIOi8sPzjlipmQ8HTReazYOvrsdbQp0cMx+Ds1e054B11GrytHMOBt5dXBOu42s2X8rzp9Ish3WqMQVrF6FacQY/34n+ZiOE4Trq4D/7tuOZGlnSS3nscnt9h9dCtZK109jiSE9RyHViGIAgVtN/91bpxxcUME3epyKN4qU1/Afxmf6xGbyn0pjTz6cmPpPrh7eX/Ka5UIBBahoyk+v0b7zoVpqNQ/9y2F6xpnYqltqx5Ukkp2iSfqTPHx50dwWbHlVPhODfXdfXnEQ03vr6YDzNoJd2rGoyXH+mU8TWQD6okynmw07h4BbXSncTVC5BlDkx4BlIFR2cJ3Rx5kaPnhp8JgqFZdAkhtsSv9uUUcHECddeXsJ6Da+j2ZO6ieYHBibS4aXMJc9nb01jxKPquFsCZ6Chin1nANR7IpHoVmNriUWPps63seCAQ9fB0jBhbzaiLpJNzqiriRD/saFaGGzxv1Q1eUBs7VfY7olgIGjoSNM73ZkBsft+U77rLga5emlV8p6o4CrYHHvBAa3GgGJLQ3ROn6gqMR7h/5zh/W5cRtSit+XJ3mfvURnhJc9gGUqpQ9NXEhgAwc3rInBmUM6TGoa5Y7pljyVGz
    #secure: 1EY0PW6l+4E/ZiuaRlC8WHb8v2J6o+YWksH852D5wIVfRnWBC6Ih6bPQMSwQ1Smm71oEOrsd8WJsabgdIkZIxinJ4chtLNBEjx2Wm32JuQziI+jvxc+Q+9YUtwrijB6xP2jHPA0n5wLEE1yHiicn6FFTFcXMJnOpizKcVkU9CgAywwJC+hXp17Vmp96jkfoDT9T+gPRSlB+N/GZubiaVXrSobSv0QTqyziDkBYRHg/DfElTuSkigaX/fDaF5OZ7jdM9QF0Th6uIHxW+OdBqb+xKZ09smfvWwkjo/1u8AsSnUR4+/mxeKXkV72w4py1zGPH4hXVOT+OOzWnSAvlR2Gwl7oAkOdoexi9X7o05Oajm5FLzFiqAzOz2ElBejPYdopqGV2xHhOAYOsLI32fq/P8NKX3gIYbRayLW/GCUE5biUDcBGVKeoU5qIMhoKF1Nhh5BOhvp/3OLKW68e+eejHD/yrN95P0yNhyzQQQl0bqhd6GPIBiFk/wPXtiqg6Pf2B8UXKzu2xtxBB2SiRRnkcZUjRi8KjlRGvIALYhWu9syCTN+TQIe6oxGh7f3j7tUyKFbATCAz6BJEz5mJtNeNCmTeUASvX0TkH7aMuumgd15nmdpSEy2sIS6gMjD026yUNU48PSBL91R71+hBFv0B6Ts89Azidc0x6GGX5204Sg4=
  DOCKER_USER:
    secure: CbwbpNPxLV9AwhjSpIz7LA==
  DOCKER_PASS:
    secure: /T9ITfudL23Ga+Mz7oRaVA==
  WORKBENCH_ENVIRONMENT:
    secure: /0UAqpwPkUwhtSS6lpKMBHZ8ljEtyTr5h3VPFqsliGLsVg8u/WLCPcwPpJOm1xpglFrEuY5lQc9ekyZ4BS6PB3rL5hfhvI1+T0zD9EMIaN+1Uo9AGU3Dc6PFzeaxT3oZBBRgzdsHeOaicVhgai6xOexBtPEZzWfXDYtxjOfybV4BmFA/hk7u7RCnkRodG6z2IiCUmXYIQbxOLyKDfbVOUVbqnYlPoYdzcZY95h2yyvik03N2vYfCtuqa/YG9NFXg0VnB/iXnlT0zfETQ9LxXJqy7WCEjgouDgZXAgPL6/XHvZW1vNfLnfn9mawqCRFVMVqXSQntma418dPc3SBgnKT6hBSn7b/VtmhJ11FpEaL7PSSl2fAGz0hF15KSQNwIyEr77niMYKgcTCVI+9i8v/WULYJKl751URnMaC3H2eXlUugOpQ34qKOV037/h07m6OrMrpOxEgyjWmkjdzzyBs6qsiQ07Xk7Fb2HooRyMUECamBPC969v5qTiUU3TXb0Ec5ssxvjpaIig5iYpfn4DbCkFo8D80R75YUXByipcPezbvAY+yXZW/VnC2UT1JdB1iRVnyb3QzBic6q8QQHnteyYfGii/crPpkBXpzWzNHp+yxLO+f7eHq+rcJu3EU3JDZAw4fUUcjil8BHWKRzDzUKaTjBbZtb2mTStgkpOlUBbAgFwecnYGanTEAQnBQJN507Yc9A/U7gIkYtI2MApI0FM6RB51bSt7wer3KrocBDCHtzHInHYPe45/1qmxPaqw0BrCdUJjIZsCy/l1mhN9N1dYuyi7TdWwHvjUAW+F8ekvC9PZ1tMEKq/z2eybPz3XTtkLuy7w9JU0caTLXPe3Hs0Sa29HkqAuPJ2KyPcT3XZ5eBHi7QEFF2IcukusZdEhx15qH4OFjWQxrrqZX5oKrJFnmSaI5WNxnf1yKp0eVAZz8Pce5fXZHud1axwC8Tr2Lq/DyxbQt5efJB00Gr6YRayDfwSnqJbgTEOR0fvwCJy4AIhg/h1JigwBgtK64jAnopFKvNxxJouFkrveI8CiqaK12DoFwICqWiWye3kirhNemjZOXT4HJqh5EOfqO0spjuBCmSK8CD6kuWzTUemZweAq5Mb5qmmMkwKXaw/iRmnCbTpB9BGCy/+RqxfcvIOpkRj/IKDu3tRQ3Gw5ObkpGLg57qVlgufYMaxUy3qd/UEqAOpV9QQDimwOKEBn1GfP
  HOBBES_PAT:
    secure: FMSdnVu01kCl/h3wLYiJfrZh9g8XCScl5sT98lVFr8KakwD9C5Lsqs01fn4o7DwX7zu+voHMzTqJ+eE+eTP/j63LoH5DHq81hW2w0Rq6EOEXg1EAUolVHsVerSUAXzfpwnvRHzagS9pD6MX7/n7813lHo9vFL4lIZeqmc1oK/eFy4trd2cGfwbrgxFY2NZnzpzY2R9vVHTCiIJuDS33BuQ==
  PM_APIKEY:
    secure: ujCKbQHfvl9fiBouXlRQH9yn/EgkW5nFHauiPeNbSwu7eJm4Y0S4It0+6DVwM/CjxwTUKof64cXLgVzEBmnSi6JfqB2UZRMeY95HGSK/JOM=
  # Disable Powershell on Linux machines
  APPVEYOR_YML_DISABLE_PS_LINUX: "true"
  # Changes ownership of minikube config dirs to running user
  CHANGE_MINIKUBE_NONE_USER: "true"
  # Set kubeconfig and minikube paths
  KUBECONFIG: "/home/appveyor/.kube/config"
  MINIKUBE_HOME: "/home/appveyor/kubernetes"
  # Disable prompts for CI
  MINIKUBE_WANTUPDATENOTIFICATION: "false"
  MINIKUBE_WANTREPORTERRORPROMPT: "false"

services:
  - docker

install:
  - docker version
  - dotnet tool install --global fake-cli
  - dotnet tool install --global paket
  - npm install -s -g --unicode=false newman@4.6.1
  
  - curl -sL https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl -o kubectl
  - chmod +x kubectl
  - sudo mv kubectl /usr/local/bin/
  
  - curl -sL https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 -o minikube
  - chmod +x minikube
  - sudo mv minikube /usr/local/bin/

  - sudo apt install conntrack
  
before_build:
  - mkdir "c:\projects\hobbes\hobbes.server\db\data"
  - sudo CHANGE_MINIKUBE_NONE_USER=true MINIKUBE_HOME=${MINIKUBE_HOME} minikube start --vm-driver=none --memory=4096
  - eval $(minikube docker-env) 
  - echo ${ENV_FILE} | kubectl apply -f -

build_script:
  - docker login -u="${DOCKER_USER}" -p="${DOCKER_PASS}" 
  - fake build --target Rebuild
  
test_script:
  - source functions.sh
  - export APP=(configurations gateway uniformdata azuredevops calculator syncronization db)
  - start
  - awaitRunningState
  #- logs azu -f
  - front_url=$(minikube ip)":30080"
  - db_url=$(minikube ip)":30084"
  - curl http://${front_url}/ping
  - NAME=$(kubectl get pods -l app=gateway -o name) 
  - newman run https://api.getpostman.com/collections/4127812-d535bce5-ad9a-4346-acb4-311c8443c478?apikey=${PM_APIKEY} -e https://api.getpostman.com/environments/4127812-b0dfd968-9fc7-406b-b5a4-11bae0ed4b47?apikey=${PM_APIKEY} --env-var "front"=${front_url} --env-var "dburl"=${db_url} --env-var "collectordburl"=${db_url}
  - newman run https://api.getpostman.com/collections/9463780-a7355a7a-5fe6-42b5-a1ed-877f3c9bc2f7?apikey=${PM_APIKEY} -e https://api.getpostman.com/environments/4127812-b0dfd968-9fc7-406b-b5a4-11bae0ed4b47?apikey=${PM_APIKEY} --env-var "front"=${front_url} --env-var "dburl"=${db_url} --env-var "collectordburl"=${db_url} --env-var "pat"=${HOBBES_PAT}
 
#deploy_script:
  #- fake build --target pushdocker