version: 1.0.{build}
image: Visual Studio 2019

environment:
  DOCKER_USER:
    secure: CbwbpNPxLV9AwhjSpIz7LA==
  DOCKER_PASS:
    secure: /T9ITfudL23Ga+Mz7oRaVA==
  WORKBENCH_ENVIRONMENT:
    secure: VeWoaKDYLSvaT7Twdm5oF+4K7uh7R/0/CRQdv8PNPpUR1bArdSFLj2cYSxFRYd1sa7lztDWzOweGZEkl6ufUGPKDi3NWZdDv0CcwrpWHboEMYKYr/4/cbbX/kYsILdqH8gpP7C99G/r1gcLk/qmofRouRlSowkfpREmwboNCEalhkJxcoOmLP90Bj9+1I3tergY+RMOYK1ZJF52zYIcp7Ie0Oe3Q24qNCfbIBGqXvqokU7LPWeZyLh+qPrATOl3sTPZcWySH185yHNAs62y9/2v2OiDSsSiRwmQQyDmEfruDf3PpObXCrrPvhhUJN+0yL0yAvePhPwxhf7tqEuiHf8SBhcsgeKQKbhVpYwWDmE3y+kaVZY+CsWRezTVq2e77

dotnet_csproj:
  patch: true
  file: '**\hobbes.server.fsproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
install:
  - docker version
  - dotnet tool install fake-cli -g
  - dotnet tool install --global --version 5.198.0 paket

before_build:
  - paket install
  - mkdir "c:\projects\hobbes\hobbes.server\db\data"

build_script: 
  - fake build --target build
  - fake build --target builddocker

test_script:
  - fake build --target test

after_test:
  - npm install -s -g --unicode=false newman
  - newman run --disable-unicode .\hobbes.server\db\Postman_collections\Smoktests.json -e .\hobbes.server\db\Postman_collections\Production_environment.json

deploy_script:
  - docker login -u="%DOCKER_USER%" -p="%DOCKER_PASS%"
  - fake build --target Publish

