# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: 'Flowerpot(6df631a2-f66b-4e70-8f3c-4630dca28cbf)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az acr login --name hobbes'

# Need go 1.13 or higher
- task: GoTool@0
  inputs:
    version: '1.13'
- script: GO111MODULE=on GOPATH=$tmpGoPath go get sigs.k8s.io/kustomize/kustomize/v3
  displayName: Go get kustomize


- script: |
    unset GOPATH
    unset GO111MODULES
    git clone https://github.com/kubernetes-sigs/kustomize
    cd kustomize
    git checkout kustomize/v3.2.3
    (cd kustomize; go install .)
    ~/go/bin/kustomize version
  displayName: Install Kustomize
- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'
- script: dotnet tool update fake-cli
  displayName: Install Fake
  
- task: NuGetToolInstaller@1
- script: echo "$(ENV_FILE)"

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'

# Download Minikube and it's prerequisites
- script: sudo apt-get install conntrack && set -e && export CHANGE_MINIKUBE_NONE_USER=true && sudo mount --make-rshared /
  displayName: Minikube prerequisites  

- script: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
  displayName: Downloading Minikube

- script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  displayName: Docker login

#- script: docker login https://docker.pkg.github.com -u="$GIT_USER" -p="$GIT_PASS"
- script: docker pull gcr.io/k8s-minikube/kicbase:v0.0.11
  displayName: Pull minikube image

# Start Minikube
- script: minikube start --driver docker --base-image gcr.io/k8s-minikube/kicbase:v0.0.11
  displayName: Start Minikube

# Fix permissions issue in AzurePipelines
- script: sudo chmod --recursive 777 $HOME/.minikube && sudo chmod --recursive 777 $HOME/.kube && minikube update-context
  displayName: Fix permissions

# Set up cluster
- script: echo "$(ENV_FILE)" | kubectl apply -f -
  displayName: Apply kubernetes environment file
  
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Flowerpot(6df631a2-f66b-4e70-8f3c-4630dca28cbf)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      source functions.sh 
      az acr login --name hobbes
      docker pull hobbes.azurecr.io/app:latest
      docker push hobbes.azurecr.io/app:latest
      build PushApps
      docker images
  env:
    FEED_PAT: $(FEED_PAT)
    VERSION: "1.2021.$(Build.BuildNumber)"   
  displayName: Build the world

- script: |
    source functions.sh && applyProductionYaml
  displayName: Setup production yaml
 
- script: source functions.sh && cd kubernetes && kubectl apply -f test.yaml
  displayName: Apply production yaml to minikube
  
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Flowerpot(6df631a2-f66b-4e70-8f3c-4630dca28cbf)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials --name hobbes-kub --resource-group hobbes-rg
      kubectl get all
      cd kubernetes
      ls
      echo "$(ENV_FILE)" | kubectl apply -f -
      kubectl apply -f test.yaml