  # ASP.NET

# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GoTool@0
  inputs:
    version: '1.13'
- script: GO111MODULE=on GOPATH=$tmpGoPath go get sigs.k8s.io/kustomize/kustomize/v3
# Need go 1.13 or higher

- script: unset GOPATH &&
          unset GO111MODULES &&
          git clone https://github.com/kubernetes-sigs/kustomize &&
          cd kustomize &&
          git checkout kustomize/v3.2.3 &&
          (cd kustomize; go install .) &&
          ~/go/bin/kustomize version
  displayName: Install Kustomize
- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'

- script: source prodFunctions.sh && applyProductionYaml
  displayName: Setup production yaml

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Flowerpot(6df631a2-f66b-4e70-8f3c-4630dca28cbf)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az aks get-credentials --name hobbes-kub --resource-group hobbes-rg && 
                   kubectl get all &&
                   cd kubernetes &&
                   ls &&
                   echo "$(ENV_FILE)" | kubectl apply -f - &&
                   kubectl apply -f test.yaml'

