# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetToolInstaller@1

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'

- task: Npm@1
  inputs:
    command: 'install'

- script: 'set -e'
- script: 'export CHANGE_MINIKUBE_NONE_USER=true'
# Make root mounted as rshared to fix kube-dns issues.
- script: 'sudo mount --make-rshared /'
    
# Download minikube.
- script: 'curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/'
  displayName: 'Downloading Minikube'
- script: 'echo "--> Starting minikube"'
- script: 'sudo minikube start --vm-driver=none --bootstrapper=kubeadm --kubernetes-version=v1.18.0'
    
# Fix permissions issue in AzurePipelines
- script: 'sudo chmod --recursive 777 $HOME/.minikube'
- script: 'sudo chmod --recursive 777 $HOME/.kube'
    
# Fix the kubectl context, as it's often stale.
- script: 'minikube update-context'