# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetToolInstaller@1

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'

- task: Npm@1
  inputs:
    command: 'install'

# Install dotnet tools
- script: dotnet tool install --global fake-cli
  displayName: Install Fake
- script: dotnet tool install --global paket
  displayName: Install Paket

# Download Minikube and it's prerequisites
- script: sudo apt-get install conntrack && set -e && export CHANGE_MINIKUBE_NONE_USER=true && sudo mount --make-rshared /
  displayName: Minikube prerequisites  

- script: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
  displayName: Downloading Minikube

# Start Minikube
- script: sudo minikube start --vm-driver=none --bootstrapper=kubeadm --kubernetes-version=v1.18.0
  displayName: Start Minikube

# Fix permissions issue in AzurePipelines
- script: sudo chmod --recursive 777 $HOME/.minikube && sudo chmod --recursive 777 $HOME/.kube && minikube update-context
  displayName: Fix permissions

# Set up cluster
- script: ip=$(minikube ip)
  displayName: Save Minikube ip
- script: eval $(minikube docker-env)
  displayName: Set build environment inside Cluster
- script: cd kubernetes && echo $ENV_FILE | kubectl apply -f - && cd ..
  displayName: Apply kubernetes environment file
  
# Build
- script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- script: fake build --target buildfortest --parallel 8

