version: "3.7"

services:
  hobbes:
    image: hobbes.server
    container_name: hobbes
    expose:
      - 8085
    ports:
      - 8085:8085
    environment:
      - COUCHDB_USER=${COUCHDB_USER} 
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}
      - KEY_SUFFIX=${KEY_SUFFIX}
      - DB_SERVER_URL=http://db-svc:5984/
      - AZURE_TOKEN_KMDDK=${AZURE_TOKEN_KMDDK}
      - AZURE_TOKEN_TIME_PAYROLL_KMDDK=${AZURE_TOKEN_TIME_PAYROLL_KMDDK}

  db-svc:
    image: apache/couchdb
    container_name: db-svc
    environment:
      - COUCHDB_USER=${COUCHDB_USER} 
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    expose: 
      - 5984
    ports:
      - 5984:5984
    volumes:
      - ./hobbes.server/db/data:/opt/couchdb/data
  azuredevopscollector:
    image: collectors.azuredevops
    container_name: azuredevopscollector
    expose:
      - 8085
    environment:
      - COUCHDB_USER=${COUCHDB_USER} 
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}
      - DB_SERVER_URL=http://collectordb-svc:5984/
  collectordb-svc:
    image: apache/couchdb
    container_name: collectordb-svc
    environment:
      - COUCHDB_USER=${COUCHDB_USER} 
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    expose: 
      - 5984
    volumes:
      - ./collectors/db/data:/opt/couchdb/data
