version: "3.7"

services:
  hobbes:
    image: hobbes.server
    container_name: hobbes
    expose:
      - 8085
    ports:
      - 8085:8085
    environment:
      - COUCHDB_USER=admin 
      - COUCHDB_PASSWORD=password
      - SERVER_PORT=8085
      - KEY_SUFFIX=2804de67ba6979c756e8759e44fe4
      - DB_SERVER_URL=http://db-svc:5984/
      - AZURE_TOKEN=abcdef
  db-svc:
    image: apache/couchdb
    container_name: db-svc
    environment:
      - COUCHDB_USER=admin 
      - COUCHDB_PASSWORD=password
    expose: 
      - 5984
    ports:
      - 5984:5984
    volumes:
      - ./hobbes.server/db/data:/opt/couchdb/data
  azuredevopscollector:
    image: kmdrd/hobbes-collectors.azuredevops
    container_name: azuredevopscollector
    expose:
      - 8085
    environment:
      - COUCHDB_USER=admin 
      - COUCHDB_PASSWORD=password
      - DB_SERVER_URL=http://collectordb:5984/
      - SERVER_PORT=8085
  collectordb:
    image: apache/couchdb
    container_name: collectordb
    environment:
      - COUCHDB_USER=admin 
      - COUCHDB_PASSWORD=password
    expose: 
      - 5984
    volumes:
      - ./collectors/db/data:/opt/couchdb/data
