apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sync
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - curl -X GET http://configurations-svc:8085/sources; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure