apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sync
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - curl -s -X GET "http://192.168.99.100:30093/sources/azure%20devops" | rev | cut -d'[' -f1 | rev | cut -d']' -f1; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure