- op: replace
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: Always

- op: replace
  path: /spec/template/spec/containers/0/image
  value: hobbes.azurecr.io/hobbes-calculator:latest
    
- op: add
  path: /spec/template/spec/imagePullSecrets/name
  value: acr-secret