apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - metrics-server.yaml
  - prod_patches/unkustomizable.yaml
  - db-deployment.yaml
  - db-svc.yaml
  - rabbitmq-controller.yaml
  - rabbitmq-service.yaml
  
patchesJson6902:
  #- target:
  #    group: apps
  #    version: v1
  #    kind: Deployment
  #    name: db
  #  path: prod_patches/db-prod.yaml