apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium-delete
  resources:
    requests:
      storage: 5Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-premium-delete
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed
---
apiVersion: batch/v1
kind: Job
metadata:
    name: sync
spec:
    template:
    spec:
        containers:
        - envFrom:
            - secretRef:
                name: env
            name: sync
            imagePullPolicy: Always
            image: kmdrd/hobbes-syncronization:latest
        restartPolicy: Never
    backoffLimit: 4