apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-disk
  labels:
    volume: db-disk
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath: 
    path: "data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium-delete
  resources:
    requests:
      storage: 5Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-premium-delete
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed