FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

WORKDIR /source
ONBUILD COPY --from=build /source .


RUN apt-get update \
  && apt-get install -y --no-install-recommends unzip \
  && apt-get install -y procps \
  && rm -rf /var/lib/apt/lists/* \ 
  && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg