FROM mcr.microsoft.com/dotnet/core/sdk:3.1
WORKDIR /source

RUN apt-get update
RUN apt-get install mono-complete -y

ENV PATH="$PATH:/root/.dotnet/tools"
RUN dotnet tool install --global Paket
RUN echo $(paket --version) 
