
FROM kmdrd/base
RUN apt-get update || apt-get update
RUN apt-get install -y unzip procps 
RUN curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l ~/vsdbg
ONBUILD COPY /deploy /
WORKDIR /Server