FROM kmdrd/sdk:app AS build

# final stage/image
FROM kmdrd/aspnet:latest

ARG WORKER_NAME

ENV EP="dotnet ${WORKER_NAME}.worker.dll"

WORKDIR /app
COPY --from=build /app .

ENTRYPOINT echo $EP && $(echo $EP)