ARG SDK_ENV=sdk:latest
FROM kmdrd/${SDK_ENV}

ENV BUILD_ENV docker

COPY .lib/ ../.lib/

# copy and publish app and libraries
COPY services/shared/ /services/shared/

COPY paket.lock paket.dependencies ./
COPY /.paket /.paket
RUN mono /.paket/paket.exe restore

ONBUILD COPY ./src/ .
ONBUILD RUN dotnet publish -c release -o /app
