FROM kmdrd/sdk:hobbes AS build

# final stage/image
FROM kmdrd/aspnet:latest

ARG SERVICE_NAME
ENV DB_SERVER_URL http://db-svc:5984
ENV EP="dotnet ${SERVICE_NAME}.dll"

WORKDIR /app
COPY --from=build /app .

ENTRYPOINT echo $EP && $(echo $EP)