FROM kmdrd/sdk:app AS build

# final stage/image
FROM kmdrd/aspnet:latest

ARG WORKER_NAME
ENV DB_SERVER_URL http://db-svc:5984
ENV EP="dotnet ${WORKER_NAME}.worker.dll"
ENV USER guest
ENV PASSWORD guest
ENV HOST "rabbitmq-service"
ENV PORT 5672
ENV DB_SERVER_URL http://db-svc:5984

WORKDIR /app
COPY --from=build /app .

ENTRYPOINT echo $EP && $(echo $EP)