FROM mcr.microsoft.com/dotnet/core/sdk:3.1
WORKDIR /source

RUN apt-get update
RUN apt-get install mono-complete -y

ENV PATH="$PATH:/root/.dotnet/tools"
RUN dotnet tool install --global Paket
RUN echo $(paket --version) 

RUN apt-get update && \
    apt-get install -y unzip procps && \
    curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l ~/vsdbg; \