FROM mcr.microsoft.com/dotnet/core/sdk:3.1
WORKDIR /source

RUN apt-get update
RUN apt-get install mono-complete -y

ENV PATH="$PATH:/root/.dotnet/tools"
RUN dotnet tool install --global Paket

ONBUILD COPY paket.dependencies .
ONBUILD COPY .paket/ ../.paket

ONBUILD RUN paket install