// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("1.1")>]
[<assembly: AssemblyTitleAttribute("Hobbes server")>]
[<assembly: AssemblyMetadataAttribute("hash","454a22")>]
[<assembly: AssemblyFileVersionAttribute("1.1")>]
[<assembly: AssemblyProductAttribute("Hobbes server")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "1.1"
    let [<Literal>] AssemblyTitle = "Hobbes server"
    let [<Literal>] AssemblyMetadata_hash = "454a22"
    let [<Literal>] AssemblyFileVersion = "1.1"
    let [<Literal>] AssemblyProduct = "Hobbes server"
