// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyTitleAttribute("Hobbes server")>]
[<assembly: AssemblyMetadataAttribute("hash","a41e4d")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyTitle = "Hobbes server"
    let [<Literal>] AssemblyMetadata_hash = "a41e4d"
