apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - localdata-deployment.yaml
  
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: localdata
    path: prod_patches/localdata-prod.yaml