apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurations
spec:
  template:
    spec:
      containers:
      - imagePullPolicy: Always
        image: hobbes.azurecr.io/configurations
        name: configurations
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
      imagePullSecrets:
      - name: acr-secret
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: configurations-svc
spec:
  selector:
    app: configurations
  type: ClusterIP