apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurations
spec:
  template:
    spec:
      containers:
      - imagePullPolicy: Always
        image: hobbes.azurecr.io/configurations
        name: configurations
      imagePullSecrets:
      - name: acr-secret
status: {}