apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
  template:
    spec:
     containers:
      - volumeMounts:
        - mountPath: "/opt/couchdb/data"
          name: volume
     volumes:
     - name: volume
       persistentVolumeClaim:
         claimName: db-disk
     restartPolicy: Always
status: {}
