apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  template:
    spec:
      containers:
      - imagePullPolicy: Always
        image: hobbes.azurecr.io/gateway
        name: gateway
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
      imagePullSecrets:
      - name: acr-secret
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  selector:
    app: gateway
  type: LoadBalancer