apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniformdata
spec:
  template:
    spec:
      containers:
      - imagePullPolicy: Always
        image: hobbes.azurecr.io/uniformdata
        name: uniformdata
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1
            memory: 1000Mi
      imagePullSecrets:
      - name: acr-secret
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: uniformdata-svc
spec:
  selector:
    app: uniformdata
  type: ClusterIP