apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
spec:
  template:
    spec:
      containers:
      - imagePullPolicy: Always
        image: hobbes.azurecr.io/rest
        name: rest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1
            memory: 1000Mi
      imagePullSecrets:
      - name: acr-secret
status: {}