apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
    - ../

patchesStrategicMerge:
  - db-volume.yaml
  - db-deployment.yaml
  - db-svc.yaml
  - azuredevops-deployment.yaml
  - calculator-deployment.yaml
  - configurations-deployment.yaml
  - configurations-svc.yaml
  - gateway-deployment.yaml
  - gateway-svc.yaml
  - git-deployment.yaml
  - rabbitmq-svc.yaml
  - syncronization-job.yaml
  - uniformdata-deployment.yaml
  - uniformdata-svc.yaml