apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: syncronization-scheduler
spec:
  schedule: "* */24 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - envFrom:
            - secretRef:
                name: env
            name: sync
            imagePullPolicy: Never
            image: syncronization
          restartPolicy: OnFailure