apiVersion: apps/v1
kind: Deployment
metadata:
  name: azuredevopscollector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azuredevopscollector
  template:
    metadata:
      labels:
        app: azuredevopscollector
    spec:
      containers:
      - env:
        - name: COUCHDB_PASSWORD
          value: password
        - name: COUCHDB_USER
          value: admin
        - name: KEY_SUFFIX
          value: 2804de67ba6979c756e8759e44fe4
        - name: SERVER_PORT
          value: "8085"
        - name: DB_SERVER_URL
          value: http://collectordb-svc:5984/
        imagePullPolicy: Always
        image: kmdrd/hobbes-collectors.azuredevops:alpha
        name: collectors-azuredevops
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: azuredevopscollector-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8085
    nodePort: 30090
  selector:
    app: azuredevopscollector
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: collectordb
spec:
    selector:
    matchLabels:
        app: collectordb
    template:
    metadata:
        labels:
        app: collectordb
    spec:
        volumes:
        - name: collectordb-storage
        persistentVolumeClaim:
            claimName: collectordb-volume-claim
        containers:
        - env:
        - name: COUCHDB_PASSWORD
            value: password
        - name: COUCHDB_USER
            value: admin
        image: apache/couchdb
        name: collectordb
        ports:
        - containerPort: 5984
        volumeMounts:
        - name: collectordb-storage
            mountPath: /opt/couchdb/data
        restartPolicy: Always
status: {}
---
    
apiVersion: v1
kind: PersistentVolume
metadata:
  name: collectordb-volume
  labels:
    volume: collectordb-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath: 
    path: "../collectors/db/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: collectordb-volume-claim
spec:
  storageClassName: standard
  selector:
    matchLabels:
      volume: collectordb-volume
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: db
spec:
    selector:
    matchLabels:
        app: db
    template:
    metadata:
        labels:
        app: db
    spec:
        volumes:
        - name: db-storage
        persistentVolumeClaim:
            claimName: db-volume-claim
        containers:
        - env:
        - name: COUCHDB_PASSWORD
            value: password
        - name: COUCHDB_USER
            value: admin
        image: apache/couchdb
        name: db
        ports:
        - containerPort: 5984
        volumeMounts:
        - name: db-storage
            mountPath: /opt/couchdb/data
        restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
    name: db-svc
spec:
    type: NodePort
    ports:
    - name: "5984"
    port: 5984
    targetPort: 5984
    nodePort: 30084
    selector:
    app: db
status:
    loadBalancer: {}
---

apiVersion: v1
kind: PersistentVolume
metadata:
    name: db-volume
    labels:
    volume: db-volume
spec:
    capacity:
    storage: 10Gi
    accessModes:
    - ReadWriteMany
    hostPath: 
    path: "../hobbes.server/db/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: db-volume-claim
spec:
    storageClassName: standard
    selector:
    matchLabels:
        volume: db-volume
    accessModes:
    - ReadWriteMany
    resources:
    requests:
        storage: 3Gi
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hobbes-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hobbes-server
  template:
    metadata:
      labels:
        app: hobbes-server
    spec:
      containers:
      - env:
        - name: COUCHDB_PASSWORD
          value: password
        - name: COUCHDB_USER
          value: admin
        - name: KEY_SUFFIX
          value: 2804de67ba6979c756e8759e44fe4
        - name: SERVER_PORT
          value: "8085"
        imagePullPolicy: Always
        image: kmdrd/hobbes-hobbes.server:alpha
        name: hobbes-server
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
    name: hobbes-server-svc
spec:
    type: NodePort
    ports:
    - port: 80
    targetPort: 8085
    nodePort: 30080
    selector:
    app: hobbes-server