apiVersion: apps/v1
kind: Deployment
metadata:
  name: azuredevops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azuredevops
  template:
    metadata:
      labels:
        app: azuredevops
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: env
        imagePullPolicy: Never
        image: azuredevops
        name: hobbes-azuredevops
        resources:
          requests:
            cpu: 100m
            memory: 2800Mi
      restartPolicy: Always
status: {}