apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: env
        imagePullPolicy: Never
        image: calculator
        name: hobbes-calculator
        resources:
          requests:
            cpu: 300m
            memory: 300Mi
      restartPolicy: Always
status: {}