apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: env
        imagePullPolicy: Never
        image: calculator
        name: calculator
        resources: {}
        ports:
          - containerPort: 4024
          - containerPort: 3702
            protocol: UDP 
      restartPolicy: Always
status: {}