apiVersion: v1
kind: Service
metadata:
  name: collectors-azuredevops-svc
spec:
  type: NodePort
  ports:
  - port: 8085
    targetPort: 8085
    nodePort: 30090
  selector:
    app: collectors-azuredevops