apiVersion: apps/v1
kind: Deployment
metadata:
  name: collectordb
spec:
  selector:
    matchLabels:
      app: collectordb
  template:
    metadata:
      labels:
        app: collectordb
    spec:
      volumes:
      - name: collectordb-storage
        persistentVolumeClaim:
          claimName: collectordb-volume-claim
      containers:
      - env:
        - name: COUCHDB_PASSWORD
          value: password
        - name: COUCHDB_USER
          value: admin
        imagePullPolicy: Never
        image: kmdrd/couchdb
        name: collectordb
        ports:
        - containerPort: 5984
        volumeMounts:
        - name: collectordb-storage
          mountPath: /opt/couchdb/data
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: collectordb-svc
spec:
  type: NodePort
  ports:
  - name: "5984"
    port: 5984
    targetPort: 5984
    nodePort: 30094
  selector:
    app: collectordb
status:
  loadBalancer: {}
---
