apiVersion: apps/v1
kind: Deployment
metadata:
  name: collectors-azuredevops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collectors-azuredevops
  template:
    metadata:
      labels:
        app: collectors-azuredevops
    spec:
      containers:
      - env:
        imagePullPolicy: Never
        image: collectors.azuredevops
        name: collectors-azuredevops
        envFrom:
        - secretRef:
            name: env
      restartPolicy: Always
status: {}
