
apiVersion: v1
kind: PersistentVolume
metadata:
  name: collectordb-volume
  labels:
    volume: collectordb-volume
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath: 
    path: "../collectors/db/data"

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: collectordb-volume-claim
spec:
  storageClassName: standard
  selector:
    matchLabels:
      volume: collectordb-volume
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  