apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configurations
  template:
    metadata:
      labels:
        app: configurations
    spec:
      containers:
      - env:
        imagePullPolicy: Never
        image: hobbes.configurations
        name: hobbes-configurations
        envFrom:
        - secretRef:
            name: env
      restartPolicy: Always
status: {}