apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
     containers:
      - env:
        - name: COUCHDB_PASSWORD
          value: password
        - name: COUCHDB_USER
          value: admin
        image: kmdrd/couchdb
        name: db
        ports:
        - containerPort: 5984
        volumeMounts:
        - mountPath: "/opt/couchdb/data"
          name: volume
     volumes:
     - name: volume
       persistentVolumeClaim:
         claimName: db-disk
     restartPolicy: Always
status: {}
