apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - imagePullPolicy: Always
        image: kmdrd/hobbes-front:alpha
        name: front
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443