apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
data:
  nginx.conf: |-
    location /jens {
        return 200 "hello"
      }

      location /oauth2 {
          set $upstream http://oauth-svc:4180;
          proxy_pass $upstream;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Scheme $scheme;
          proxy_connect_timeout 1;
          proxy_send_timeout 30; 
          proxy_read_timeout 30; 
      }
      
      location /key {
          auth_request /oauth2/auth;
          error_page 401 = /oauth2/sign_in;
          auth_request_set $user $upstream_http_x_auth_request_user;
          proxy_set_header X-Forwarded-User $user;
          proxy_set_header Host $host;
          proxy_redirect off;
          proxy_set_header X-Real-IP $remote_addr;
          set $upstream http://hobbes-server-svc:8085/;
          proxy_pass $upstream;
      }
      
      location = / {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          set $upstream http://hobbes-server-svc:8085/ping; 
          proxy_pass $upstream;
      }

      location /generate/key {
          auth_request /oauth2/auth;
          error_page 401 = /oauth2/sign_in;
          auth_request_set $user $upstream_http_x_auth_request_user;
          proxy_set_header X-Forwarded-User $user;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          set $upstream https://$http_host/key/$cookie__oauth2_proxy;
          return 302 $upstream;
      }

      location ~ /api/(.*) {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            set $upstream http://hobbes:8085/$1$is_args$args; 
            proxy_pass $upstream;
        } 