apiVersion: v1
kind: Service
metadata:
  name: hobbes-server-svc
  namespace: ingress-nginx
spec:
  ports:
  - name: "8085"
    port: 8085
    targetPort: 8085
  selector:
    app: hobbes-server
status:
  loadBalancer: {}
