apiVersion: v1
kind: Service
metadata:
  name: hobbes-server-svc
  namespace: ingress-nginx
spec:
  ports:
  - port: 80
    targetPort: 8085
  selector:
    app: hobbes-server
status:
  loadBalancer: {}
