apiVersion: v1
kind: Service
metadata:
  name: hobbes-server-svc
spec:
  ports:
  - port: 80
    targetPort: 8085
  selector:
    app: hobbes-server
  type: LoadBalancer
  loadBalancerIP: 203.0.113.32