apiVersion: apps/v1
kind: Deployment
metadata:
  name: hobbes-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hobbes-server
  template:
    metadata:
      labels:
        app: hobbes-server
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: env
        imagePullPolicy: Never
        image: hobbes.server
        name: hobbes-server
        resources: {}
      restartPolicy: Always
status: {}
