apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - local_patches/db-volume.yaml
  - db-deployment.yaml
  - db-svc.yaml
  - azuredevops-deployment.yaml
  - calculator-deployment.yaml
  - git-deployment.yaml
  - gateway-deployment.yaml
  - gateway-svc.yaml
  - rabbitmq-controller.yaml
  - rabbitmq-service.yaml
  - metrics-server.yaml
  
patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: gateway-svc
    path: local_patches/gateway-svc-dev.yaml
  - target:
      version: v1
      kind: Service
      name: db-svc
    path: local_patches/db-svc-dev.yaml