apiVersion: batch/v1
kind: Job
metadata:
  name: publish
spec:
  template:
    spec:
        containers:
        - name: publish
          imagePullPolicy: Never
          image: kmdrd/workbench
          env:
            - name: PAT
              value: "Rno8hcqr9rXXs"
        restartPolicy: Never
  backoffLimit: 4