apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    component: rabbitmq
  name: rabbitmq-service
  selfLink: /api/v1/namespaces/default/services/rabbitmq-service
spec:
  ports:
  - name: "5672"
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: "15672"
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: taskQueue
    component: rabbitmq
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
