apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: test
    meta.helm.sh/release-namespace: default
  creationTimestamp: null
  labels:
    app: rabbitmq
    app.kubernetes.io/managed-by: Helm
    chart: rabbitmq-6.26.0
    heritage: Helm
    release: test
  name: test-rabbitmq-headless
  selfLink: /api/v1/namespaces/default/services/test-rabbitmq-headless
spec:
  clusterIP: None
  ports:
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: epmd
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: amqp
  - name: dist
    port: 25672
    protocol: TCP
    targetPort: dist
  - name: stats
    port: 15672
    protocol: TCP
    targetPort: stats
  selector:
    app: rabbitmq
    release: test
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}