apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    component: rabbitmq
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:component: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":5672,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
          f:component: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl.exe
    operation: Update
    time: "2020-06-16T08:25:03Z"
  name: rabbitmq-service
  selfLink: /api/v1/namespaces/default/services/rabbitmq-service
spec:
  ports:
  - name: "5672"
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: "15672"
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: taskQueue
    component: rabbitmq
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
