apiVersion: v1
data:
  rabbitmq-erlang-cookie: R1dSUllhZWFxR0dxMWUwdWRRaHlJWDhOb3ZwMlBiZmM=
  rabbitmq-password: Z3Vlc3Q=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: test
    meta.helm.sh/release-namespace: default
  creationTimestamp: null
  labels:
    app: rabbitmq
    app.kubernetes.io/managed-by: Helm
    chart: rabbitmq-6.26.0
    heritage: Helm
    release: test
  name: test-rabbitmq
  selfLink: /api/v1/namespaces/default/secrets/test-rabbitmq
type: Opaque