apiVersion: v1
data:
  enabled_plugins: '[rabbitmq_management, rabbitmq_peer_discovery_k8s, rabbitmq_auth_backend_ldap].'
  rabbitmq.conf: |-
    ##username and password
    default_user=guest
    default_pass=CHANGEME
    ## Clustering
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.node_cleanup.interval = 10
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    # queue master locator
    queue_master_locator=min-masters
    # enable guest user
    loopback_users.guest = false
    #disk_free_limit.absolute = 50MB
    #management.load_definitions = /app/load_definition.json
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: test
    meta.helm.sh/release-namespace: default
  creationTimestamp: null
  labels:
    app: rabbitmq
    app.kubernetes.io/managed-by: Helm
    chart: rabbitmq-6.26.0
    heritage: Helm
    release: test
  name: test-rabbitmq-config
  selfLink: /api/v1/namespaces/default/configmaps/test-rabbitmq-config