apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-service
spec:
  ports:
  - name: main
    port: 5672
  - name: management
    port: 15672
  selector:
    app: taskQueue
    component: rabbitmq