apiVersion: v1
kind: Service
metadata:
  name: syncronization-svc
spec:
  type: NodePort
  ports:
  - port: 5672
    name: sys
    targetPort: 5672
    nodePort: 30567
  - port: 15672
    name: management
    targetPort: 15672
    nodePort: 31567
  selector:
    app: syncronization
