apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: syncronization-scheduler
spec:
  schedule: "*/4 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sync
            imagePullPolicy: Never
            image: syncronization
          restartPolicy: OnFailure