apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniformdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uniformdata
  template:
    metadata:
      labels:
        app: uniformdata
    spec:
      containers:
      - env:
        imagePullPolicy: Never
        image: uniformdata
        name: hobbes-uniformdata
        envFrom:
        - secretRef:
            name: env
      restartPolicy: Always
status: {}
