apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniformdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uniformdata
  template:
    metadata:
      labels:
        app: uniformdata
    spec:
      containers:
      - imagePullPolicy: Never
        image: uniformdata
        name: uniformdata
        envFrom:
        - secretRef:
            name: env
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
      restartPolicy: Always
      imagePullSecrets:
      - name: acr-secret
status: {}
