apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: env
        image: hobbes.azurecr.io/hobbes-calculator:latest
        imagePullPolicy: Always
        name: calculator
        ports:
        - containerPort: 4024
        - containerPort: 3702
          protocol: UDP
        resources: {}
      imagePullSecrets:
      - name: acr-secret
      restartPolicy: Always
status: {}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: calculator
spec:
  maxReplicas: 4
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 100
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: calculator
