apiVersion: apps/v1
kind: Deployment
metadata:
  name: localdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localdata
  template:
    metadata:
      labels:
        app: localdata
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: env
        imagePullPolicy: Never
        image: localdata
        name: localdata
        resources: {}
        env:
          - name: MAX_LOG_LENGTH
            value: "50000000"
      restartPolicy: Always
      imagePullSecrets:
      - name: acr-secret
status: {}