<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>scopeName</key>
    <string>source.hobbes</string>
    <key>fileTypes</key>
    <array>
      <string>hb</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.control.hobbes</string>
        <key>match</key>
        <string>only|else|if|then|by</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.hobbes</string>
        <key>match</key>
        <string>\b(-&gt;|=&gt;|=|int)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.values.hobbes</string>
        <key>match</key>
        <string>\b(keys|ordinals|index|missing)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.dates.hobbes</string>
        <key>match</key>
        <string>\b(date|day|week|weekday|month|year)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.aggregator.hobbes</string>
        <key>match</key>
        <string>\b(count|distinct|max|mean|median|min|stddev|sum|variance)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.filter.hobbes</string>
        <key>match</key>
        <string>\b(dense|numeric)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.other.hobbes</string>
        <key>match</key>
        <string>\b(provider|buckets|column|columns|create|rename|dense|expanding|extrapolation|format|group|index|keys|k-means|linear|maxby|minby|moving|numeric|pivot|regex|regression|rows|slice|sort)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.other.yaml.propertyName</string>
        <key>match</key>
        <string>\b[^]*:\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.other.yaml.propertyName</string>
        <key>match</key>
        <string>\s*.*:\s</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>name</key>
        <string>comment.block.markdown.hobbes</string>
        <key>begin</key>
        <string>!#</string>
        <key>end</key>
        <string>!#</string>
      </dict>
    </dict>
  </dict>
</plist>