apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: calculator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: calculator
  minReplicas: 1
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50