version: "3.7"
networks:
  internal:
  front:
services:
  azuredevopscollector:
    image: azuredevopscollector
    container_name: azuredevopscollector
    networks: 
      - internal
    expose:
      - 8086
    ports:
      - 8086:8085
    environment:
      - COUCHDB_USER=admin 
      - COUCHDB_PASSWORD=password
      - SERVER_PORT=8085
      - KEY_SUFFIX=2804de67ba6979c756e8759e44fe4
    depends_on:
      - collectordb
  collectordb:
    image: apache/couchdb
    container_name: collectordb
    environment:
      - COUCHDB_USER=admin 
      - COUCHDB_PASSWORD=password
    networks: 
      - internal
    expose: 
      - 5984
    volumes:
      - ./db/data:/opt/couchdb/data
    ports:
      - 5985:5984
